# Docker Compose override for staging environment
version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: lyricnote_staging
      POSTGRES_USER: lyricnote_staging
    ports:
      - "5433:5432"  # Different port for staging
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  redis:
    ports:
      - "6380:6379"  # Different port for staging
    volumes:
      - redis_staging_data:/data

  backend:
    environment:
      NODE_ENV: staging
      DATABASE_URL: postgresql://lyricnote_staging:${POSTGRES_PASSWORD}@postgres:5432/lyricnote_staging
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - "3001:3000"  # Different port for staging
    depends_on:
      - postgres
      - redis

  nginx:
    ports:
      - "8080:80"   # Different port for staging
      - "8443:443"
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_staging_data:
    driver: local
  redis_staging_data:
    driver: local
