version: '3.8'

# 开发环境 - 只启动数据库和 Redis
services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:16-alpine
    container_name: lyricnote-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lyricnote_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: lyricnote-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # Drizzle Studio (可选)
  drizzle-studio:
    image: node:20-alpine
    container_name: lyricnote-drizzle-studio
    working_dir: /app
    volumes:
      - ./packages/backend:/app
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lyricnote_dev
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm install -g drizzle-kit && drizzle-kit studio --port 5555 --host 0.0.0.0"
    profiles:
      - tools

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  default:
    name: lyricnote-dev-network

